#!/bin/bash

cd ~/RoboFEI-HT_2023_SOFTWARE/src
robot_number=$(python3 /home/robot_num.py)

if [ $1 = 'c' ]; then
  cd robot_bringup/config
  if [ -z $robot_number ]; then
    echo "ERRO: Not have Robot Number"
  else 
    vim robot_config$robot_number.yaml
  fi
fi
if [ $1 = 'm' ]; then
  cd control/Data
  if [ -z $robot_number ]; then
    echo "ERRO: Not have Robot Number"
  else 
    vim motion$robot_number.json
  fi
fi
if [ $1 = 'i' ]; then
  cd control/Data
  if [ -z $robot_number ]; then
    echo "ERRO: Not have Robot Number"
  else 
    vim config$robot_number.ini
  fi
fi