/**:
  ros__parameters:
    video_device: "/dev/camera"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
    av_device_format: "YUV422P"
    image_width: 640
    image_height: 480
    camera_name: "test_camera"
    camera_info_url: "package://usb_cam/config/camera_info.yaml"
    brightness: 128  #0
    contrast: 128    #16 12
    saturation: 128  #10 12
    sharpness: 138   #7 12
    gain: 0
    auto_white_balance: true
    white_balance: -1 #  0
    autoexposure: true
    exposure: 100   #   1
    autofocus: false
    focus: -1