/**:
  ros__parameters:
    video_device: "/dev/camera_lenovo"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
    av_device_format: "YUV422P"
    image_width: 640
    image_height: 480
    camera_name: "test_camera"
    camera_info_url: "package://usb_cam/config/camera_info.yaml"
    brightness: 0  #0
    contrast: 12    #16
    saturation: 12  #10
    sharpness: 12   #7
    gain: 0
    auto_white_balance: true
    white_balance: 0
    autoexposure: true
    exposure: 1
    autofocus: false
    focus: -1