# Robot 4
/**:
  ros__parameters:
    neck_up_limit   : 512
    neck_down_limit : 300
    neck_left_limit : 724
    neck_right_limit: 300
    robot_number    : 4

/neck_node:
  ros__parameters:
    neck_activate: true

    x_p_gain: 0.2
    y_p_gain: 0.1

/control:
  ros__parameters:
    body_activate : true
    walk_counter  : 10 

/decision_node:
  ros__parameters:
    FALL_ACCEL_TH: 7.0
    FALSES_FALLEN_TH: 30

/image_node:
  ros__parameters:
    img_qlty: 100 
    get_image: false
    fps_save: 2
    enable_udp: True
